services:
  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p1

    env_file:
      - ../../.env

    ports:
      - "${PGBOUNCER_PORT}:${PGBOUNCER_PORT}"

    volumes:
      - ./conf/pgbouncer.ini.template:/etc/pgbouncer/pgbouncer.ini.template:ro
      - ./conf/userlist.txt:/etc/pgbouncer/userlist.txt:ro

    command: >
      sh -c "
      envsubst < /etc/pgbouncer/pgbouncer.ini.template > /etc/pgbouncer/pgbouncer.ini &&
      exec pgbouncer /etc/pgbouncer/pgbouncer.ini
      "