services:
  pgbouncer:
    image: edoburu/pgbouncer:v1.24.1-p1
    hostname: pgbouncer
    restart: unless-stopped

    env_file:
      - ../../.env

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "${PGBOUNCER_PORT}:${PGBOUNCER_PORT}"

    volumes:
      - ./conf/pgbouncer.ini.template:/etc/pgbouncer/pgbouncer.ini.template:ro
      - ./conf/userlist.txt:/etc/pgbouncer/userlist.txt:ro
      - ./start-pgbouncer.sh:/start-pgbouncer.sh:ro

    entrypoint: ["/bin/sh", "/start-pgbouncer.sh"]

    networks:
      - jovavia-network


networks:
  jovavia-network:
    external: true
    name: jovavia-network