services:
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    restart: unless-stopped

    env_file:
      - ../../.env

    environment:
      DATA_SOURCE_URI: "${POSTGRES_HOST}:${POSTGRES_PORT}/jovavia_identity?sslmode=disable"
      DATA_SOURCE_USER: "${POSTGRES_USER}"
      DATA_SOURCE_PASS: "${POSTGRES_PASSWORD}"

    ports:
      - "${POSTGRES_EXPORTER_PORT}:9187"

    networks:
      - jovavia-network

networks:
  jovavia-network:
    external: true
    name: jovavia-network